### ISSUE TITLE
Unable to access my repository

### ISSUE THREAD

**Issue by chamberlain-trevor** [chamberlain-trevor/git_notes#3]
@cecileane @coraallencoleman

I crashed and reformatted my hard drive and now my github repository doesn't recognize my laptop. This is preventing me from interfacing with git and submitting assignments (like the binomial.py assignment that was due tonight).

Here is the error I'm getting:

```
git clone git@github.com:git@github.com:chamberlain-trevor/git_notes.git
Cloning into 'git_notes'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Thanks for the help.

**Comment by cecileane** [comment]
Hi Trevor, please submit this "binomial" assignment any time, after you fix your laptop issues.

About git: I suspect that the problem comes from the SHA key that you had in your `.ssh` folder. GitHub has the key, but the lock (on your hard drive) doesn't match. You can set up a completely new key: [instructions](https://github.com/UWMadison-computingtools-master/general-info/blob/master/git.md#communicate-with-github). You can delete the "SSH key" that is listed under your Settings in GitHub: the one that worked with your previous file before your re-formatted your hard drive. Now, that's just my guess. The issue could be somewhere else of course.
